<?php $v->layout('layout', ['title' => '4 oh 4']) ?>

<div class="container">

  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="m-5 mb-4 red display-4">*** 404 ***</h1>

      <h2> User <span class="purple">@<?=$v($username)?></span> not found </h2>
      <h1 class="m-5 mb-4 display-4">:(</h1>

      <h3>Why not <a href="<?=$v(t_text("Hey @$username, are you coming out to play ? %23DerelictIreland %23FreeTheCycleLane", 'http://cyclespaceinvaders.com', false))?>" class="red blink p-1" target="_BLANK">invite</a> them to join ?</a></h3>

      <h4> Or view profile on <a href="https://twitter.com/<?=$v($username)?>" target="_BLANK"> Twitter</a></h4>

      <a href="/contributors">
            <h4 class="my-5"><< VIEW ALL PLAYERS</h4>
            </a>
    </div>
  </div>
</div>
