
  <!-- ======= Footer ======= -->
  <section class="section-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-6">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand color-b">about</h3>
            </div>
            <div class="w-body-a">
              <p class="w-text-a color-text-a">
                This microsite aims to collate the photos and videos posted to twitter.com with the <strong>#DerelictIreland</strong> hashtag. <br>It should update every hour or so.
              </p>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-6 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand color-b">contact</h3>
            </div>
            <!-- <p class="w-text-a color-text-a">
              This site collates the
            </p> -->

            <div class="w-footer-a">
              <ul class="list-unstyled">
                <li class="color-a">
                  <span class="color-text-a">twitternet.</span> <a href="https://twitter.com/tweetphelan" target="_blank">@tweetphelan</a>
                </li>
                <li class="color-a">
                  <span class="color-text-a">interweb.</span> <a href="http://vool.ie" target="_blank">vool.ie</a>
                </li>
                <li class="color-a">
                  <span class="color-text-a">electronicmail.</span> <a href="mailto:keith@vool.ie">keith@vool.ie</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footer>

  </footer><!-- End  Footer -->
