<!-- ======= Header/Navbar ======= -->
  <nav class="navbar navbar-default navbar-trans navbar-expand-lg fixed-top">
    <div class="container">
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <a class="navbar-brand text-brand" href="/">#Derelict<span class="color-b">Ireland</span></a>
      <div class="navbar-collapse collapse justify-content-end" id="navbar">
        <ul class="navbar-nav">

          <li class="nav-item">
            <a class="nav-link <?php echo  $_SERVER['REQUEST_URI'] == '/' ? 'active' : ''; ?>" href="/">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link <?php echo  $_SERVER['REQUEST_URI'] == '/posts' ? 'active' : ''; ?>" href="/posts">Posts</a>
          </li>

          <li class="nav-item">
            <a class="nav-link <?php echo  $_SERVER['REQUEST_URI'] == '/contributors' ? 'active' : ''; ?>" href="/contributors">Contributors</a>
          </li>
        </ul>
      </div>
    </div>
  </nav><!-- End Header/Navbar -->
