            <nav class="navbar navbar-expand-sm align-items-start flex-sm-column flex-row">
                <a class="navbar-brand" href="/">CYCLE SPACE<br>INVADERS</a>
                <a href class="navbar-toggler" data-toggle="collapse" data-target=".sidebar">
                  <span class="line"></span>
                  <span class="line"></span>
                  <span class="line"></span>
                </a>
                <div class="collapse navbar-collapse sidebar">
                    <ul class="flex-column navbar-nav w-100 justify-content-between">
                        <li class="nav-item">
                            <a class="nav-link pl-0" href="#"><i class="fa fa-heart-o fa-fw"></i> <span class="">Link</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link pl-0" href="/leader-board"><span class="">LEADER BOARD</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link pl-0" href="/posts"><span class="">INVADERS</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link pl-0" href="/contributors"><span class="">PLAYERS</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link pl-0" href="/map"><span class="">MAP</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link pl-0" href="/get-involved"><span class="">GET INVOLVED</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link pl-0" href="/get-involved"><span class="blink">INSERT COIN</span></a>
                        </li>

                    </ul>
                </div>
            </nav>
