<div class="col-md-4">
  <div class="card-box-a card-shadow">
      <a href="/post/<?=$v($tweet['id'])?>" class="stretched-link">
    <div class="img-box-a">


      <?php if ($tweet['media']):
        $media = JSON_decode($tweet['media']);
        ?>

      <img src="<?=$v($media[0]->media_url_https)?>" alt="" class="img-a img-fluid">

       <?php endif; ?>
    </div>

    <div class="card-overlay">
      <div class="card-overlay-a-content">
        <div class="card-header-a">
          <h2 class="card-title-a">
            <?php
             foreach (JSON_decode($tweet['hashtags']) as $tag):
            ?>
            #<?=$v($tag)?>
            <?php
                  endforeach; ?>
          </h2>
        </div>
        <div class="card-body-a">
          </div>
        <div class="card-footer-a">
          <ul class="card-info d-flex justify-content-around">
            <li>
              <?php if(isset($tweet["username"])){ ?>
              <h4 class="card-info-title">Posted by</h4>
              <span>@<?=$v($tweet["username"])?></span>
            <?php } ?>
            </li>
            <li>
              <h4 class="card-info-title">Date</h4>
              <span><?=$v(Carbon\Carbon::parse($tweet['created_at'])->format('d/m/y'))?>
              </span>
            </li>
            <!-- <li>
              <h4 class="card-info-title">Baths</h4>
              <span>4</span>
            </li>
            <li>
              <h4 class="card-info-title">Garages</h4>
              <span>1</span>
            </li> -->
          </ul>
        </div>
      </div>
    </div>
      </a>
  </div>

</div>
