<?php $v->layout('layout') ?>


    <!-- ======= Intro Single ======= -->
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <!-- <div class="title-single-box">
              <h1 class="title-single"><?=$v($user["screenname"])?></a></h1>
              <span class="color-text-a">@<?=$v($user["username"])?></a></span>
            </div> -->
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                  <a href="/contributors">Contributors</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  <?=$v($user["screenname"])?>
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section><!-- End Intro Single -->

    <!-- ======= Agent Single ======= -->
    <section class="agent-single">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="row">
              <div class="col-md-6">
                <div class="agent-avatar-box">
                  <img src="<?=$v(largeAvatar($user["avatar"]))?>" alt="" class="agent-avatar img-fluid">
                </div>
              </div>
              <div class="col-md-5 section-md-t3">
                <div class="agent-info-box">
                  <div class="agent-title">
                    <div class="title-box-d">
                      <h1 class="title-d"><?=$v($user["screenname"])?></h1>
                      <span class="color-text-a">@<?=$v($user["username"])?></span>
                    </div>
                  </div>
                  <div class="agent-content mb-3">
                    <p class="content-d color-text-a">
                        <?=$v($user['description'])?>
                    </p>
                    <div class="info-agents color-a">
                      <p>
                        <strong>Location: </strong>
                        <span class="color-text-a"> <?=$v($user['location'])?></span>
                      </p>

                      <p>
                        <strong>Twitter: </strong>
                        <span class="color-text-a"> <a href="https://twitter.com/<?=$v($user['username'])?>" target="_blank">@<?=$v($user['username'])?></a></span>
                      </p>

                      <p>
                        <strong>Website: </strong>
                        <span class="color-text-a"> <a href="<?=$v($user['url'])?>" target="_blank"><?=$v($user['url'])?></a></span>
                      </p>

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-12 section-t8">
            <div class="title-box-d">
              <h3 class="title-d"><?=$v($user["screenname"])?>'s posts (<?=$v($total)?>)</h3>
            </div>
          </div>

          <section class="property-grid grid">
            <div class="container">
              <div class="row">

            <?php
              foreach ($tweets as $tweet) {
                  $v->insert('includes::tweet', ['tweet' =>  $tweet]);
              }
              ?>

          </div>
          </div>

        </section>

          <div class="row">
            <div class="col-sm-12">
              <nav class="pagination-a">
                <?php
                if ($total_pages >1) {
                    echo generatePageLinks($page, $total_pages, '/contributor/@'.$user["username"].'/');
                }
                 ?>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </section><!-- End Agent Single -->


<?php $v->push('scripts') ?>

    <script>
        // Some JavaScript
        $(function() {
          console.log( "ready!" );

          var myvalues = [10,8,5,7,4,4,1];
          $('.dynamicbar').sparkline(myvalues, {type: 'bar', barColor: 'green', barWidth: 20} );

        });


    </script>
<?php $v->end() ?>
