<?php $v->layout('layout', ['title' => 'Get Involved', 'card' => 'http://cyclespaceinvaders.com/img/score_card.png']) ?>

<div class="container get-involved">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="mt-5 mb-4 green">*** PLAYER UP ***</h1>

          <p class="lead">
            Have you got what it takes to help rid cycle space of the evil invaders ?
          </p>
            <p>
            In order to join all you need is a camera and a Twitter account, simply capture an invader in a cycle space and post it with the hashtag <span class="red blink">#FreeTheCycleLanes</span>.
          </p>
            <p>
            The hardest part of the game is finding a cycle path due to Ireland's poor record of developing quality cycle infrastructure, but once you located one you can be almost guarenteed to find an invader in it !.
          </p>
            <p>
            You get points for each capture, as well as extra points if you GeoTag or hashtag your location.
          </p>
            <p>Have what it takes to make the <a href="/leader-board">Leader Board</a> !
          </p>


      </div>
    </div>


<?php $v->insert('includes::score_table') ?>



 <div class="container players">
   <div class="row">
     <div class="col-lg-12 text-center">
       <h1 class="mt-2 mb-4 red">*** MULTI PLAYER ***</h1>
       <p class="lead mb-4">
         If you get bored of playing on you own, why not you join up with other players in you area !
       </p>
       <p class="">
         There is a network of cycle advocacy groups throughtout ireland who all form part of <span class="blink green">Cyclist.ie</span>- The Irish Cycling Advocacy Network.
       </p>

       </div>
     </div>


        <div class="row mt-4">

          <?php foreach ($rcpgs as $player): ?>


            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 box">
                <a href="/contributor/@<?=$v($player["username"])?>" class="" >

                  <div class="my-2">
                  <img class="mx-auto" src="<?=$v($player["avatar"])?>" data-pixelate data-reveal="false" data-value="0.4"/>
                </div>
                <div>
                    @<?=$v($player["username"])?>
                  </div>
                  <div class="location">
                      <?=$v($player["location"])?>
                    </div>
                </a>

            </div>


            <?php
            endforeach ?>

        </div>

     </div>

  </div>




<?php $v->push('scripts') ?>
    <script>
        // Some JavaScript
    </script>
<?php $v->end() ?>
