<?php $v->layout('layout', ['title' => 'Derelict site captured by @'.$data['username']]) ?>



<!-- ======= Intro Single ======= -->
<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h1 class="title-single">Post</h1>
          <span class="color-text-a">  #<?=$v($data['id'])?></span>
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="/">Home</a>
            </li>
            <li class="breadcrumb-item">
              <a href="/posts">Posts</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
              #<?=$v($data['id'])?>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section><!-- End Intro Single-->




    <!-- ======= Property Single ======= -->
    <section class="property-single nav-arrow-b">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <div id="property-single-carousel" class="swiper">
              <div class="swiper-wrapper">


                <?php

                $media = JSON_decode($data['media']);

                foreach ($media as $m):
                  switch ($m->type) {
                    case 'photo':

                    echo '<div class="carousel-item-b swiper-slide">';
                      echo '<img src="'.$m->media_url_https.'" class=""/>';
                    echo '</div>';


                      break;
                      case 'video':

                    echo'<video controls>
                            <source src="'.$m->video_info->variants[2]->url.'" type="'.$m->video_info->variants[2]->content_type.'">
                            <p>Your browser doesn\'t support HTML5 video.</p>
                          </video>';

                        break;

                    default:
                      # code...
                      break;
                  }

              endforeach;
                 ?>

              </div>
            </div>
            <div class="property-single-carousel-pagination carousel-pagination"></div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">

            <div class="row justify-content-between">
              <div class="col-md-5 col-lg-4">
                <!-- <div class="property-price d-flex justify-content-center foo">
                  <div class="card-header-c d-flex">
                    <div class="card-box-ico">
                      <span class="bi bi-cash">$</span>
                    </div>
                    <div class="card-title-c align-self-center">
                      <h5 class="title-c">15000</h5>
                    </div>
                  </div>
                </div> -->
                <div class="property-summary">
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="title-box-d section-t3">
                        <h3 class="title-d">Posted</h3>
                      </div>
                    </div>
                  </div>
                  <div class="summary-list">
                    <ul class="list">
                      <li class="d-flex justify-content-between">
                        <strong>Date:</strong>
                        <span><?=$v(Carbon\Carbon::parse($data['created_at'])->format('d/m/y'))?></span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Time:</strong>
                        <span><?=$v(Carbon\Carbon::parse($data['created_at'])->format('H:m'))?></span>
                      </li>
                    </ul>
                  </div>


                  <div class="row section-t3">
                    <div class="col-sm-12">
                      <div class="title-box-d">
                        <h3 class="title-d">Tags</h3>
                      </div>
                    </div>
                  </div>
                  <div class="amenities-list color-text-a">
                    <ul class="list-a no-margin">
                      <?php
                      foreach (JSON_decode($data['hashtags']) as $tag):
                        if (strtolower($tag) !== strtolower($_ENV['HASHTAG'])):?>

                     <li><a href="/tag/<?=$v($tag)?>">#<?=$v($tag)?></a></li>
                     <?php endif ;
                           endforeach; ?>

                    </ul>
                  </div>



                </div>
              </div>
              <div class="col-md-7 col-lg-7 section-md-t3 section-t3">
                <!-- <div class="row">
                  <div class="col-sm-12">
                    <div class="title-box-d">
                      <h3 class="title-d">Text</h3>
                    </div>
                  </div>
                </div> -->

                <div class="testimonials-content">
                                    <p class="testimonial-text">
                                      <?=$v(linkify($data['text']))?>
                                    </p>
                                  </div>

                                  <div class="testimonial-author-box">
                      <img src="<?=$v($data["avatar"])?>" alt="" class="testimonial-avatar rounded-circle">
                      <h5 class="testimonial-author">
                        <ul class="list-inline text-right ">
                           <li class="list-inline-item price-a"><a class="social-icon text-xs-center" target="_blank" href="#"><?=$v(t_like($data['id']))?></li>
                           <li class="list-inline-item price-a"><a class="social-icon text-xs-center" target="_blank" href="#"><?=$v(t_retweet($data['id']))?></li>
                           <li class="list-inline-item price-a"><a class="social-icon text-xs-center" target="_blank" href="#"><?=$v(t_reply($data['id']))?></li>
                           <li class="list-inline-item price-a"><a class="social-icon text-xs-center" target="_blank" href="#"><?=$v(t_link_tweet($data['id']))?></li>
                        </ul>
                      </h5>
                    </div>
              </div>
            </div>
          </div>
          <!-- <div class="col-md-10 offset-md-1">
            <ul class="nav nav-pills-a nav-pills mb-3 section-t3" id="pills-tab" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" id="pills-video-tab" data-bs-toggle="pill" href="#pills-video" role="tab" aria-controls="pills-video" aria-selected="true">Video</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="pills-plans-tab" data-bs-toggle="pill" href="#pills-plans" role="tab" aria-controls="pills-plans" aria-selected="false">Floor Plans</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="pills-map-tab" data-bs-toggle="pill" href="#pills-map" role="tab" aria-controls="pills-map" aria-selected="false">Ubication</a>
              </li>
            </ul>
            <div class="tab-content" id="pills-tabContent">
              <div class="tab-pane fade show active" id="pills-video" role="tabpanel" aria-labelledby="pills-video-tab">
                <iframe src="https://player.vimeo.com/video/73221098" width="100%" height="460" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
              </div>
              <div class="tab-pane fade" id="pills-plans" role="tabpanel" aria-labelledby="pills-plans-tab">
                <img src="assets/img/plan2.jpg" alt="" class="img-fluid">
              </div>
              <div class="tab-pane fade" id="pills-map" role="tabpanel" aria-labelledby="pills-map-tab">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3022.1422937950147!2d-73.98731968482413!3d40.75889497932681!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25855c6480299%3A0x55194ec5a1ae072e!2sTimes+Square!5e0!3m2!1ses-419!2sve!4v1510329142834" width="100%" height="460" frameborder="0" style="border:0" allowfullscreen></iframe>
              </div>
            </div>
          </div> -->
          <div class="col-md-12">
            <div class="row section-t3">
              <div class="col-sm-12">
                <div class="title-box-d">
                  <h3 class="title-d">Posted by:</h3>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 col-lg-4">
                <img src="<?=$v(largeAvatar($data["avatar"]))?>" alt="" class="img-fluid">
              </div>
              <div class="col-md-6 col-lg-4">
                <div class="property-agent">
                  <h4 class="title-agent"><a href="/contributor/@<?=$v($data['username'])?>"><?=$v($data['screenname'])?></a></h4>
                  <p class="color-text-a">
                    <?=$v($data['description'])?>
                  </p>
                  <ul class="list-unstyled">
                    <li class="d-flex justify-content-between">
                      <strong>Username:</strong>
                      <span class="color-text-a"><a href="/contributor/@<?=$v($data['username'])?>">@<?=$v($data['username'])?></a></span>
                    </li>

                    <?php if ($data['location']):?>
                    <li class="d-flex justify-content-between">
                      <strong>Location:</strong>
                      <span class="color-text-a"><?=$v($data['location'])?></span>
                    </li>
                      <?php endif; ?>

                    <?php if ($data['url']):?>
                    <li class="d-flex justify-content-between">
                      <strong>Web:</strong>
                      <span class="color-text-a"><a href="/contributor/@<?=$v($data['url'])?>"><?=$v($data['url'])?></a></span>
                    </li>
                    <?php endif; ?>

                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section><!-- End Property Single-->


<?php $v->push('scripts') ?>
    <script>
        // Some JavaScript
    </script>
<?php $v->end() ?>
