<?php $v->layout('layout', ['title' => 'Derelict Sites']) ?>


    <!-- ======= Intro Single ======= -->
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single"><strike>Pretty</strike> Vacant</h1>
              <span class="color-text-a"><?=$v($total)?> posts</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="/">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  Posts
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section><!-- End Intro Single-->

    <!-- ======= Property Grid ======= -->
    <section class="property-grid grid">
      <div class="container">
        <div class="row">
          <!-- <div class="col-sm-12">
            <div class="grid-option">
              <form>
                <select class="custom-select">
                  <option selected>All</option>
                  <option value="1">New to Old</option>
                  <option value="2">For Rent</option>
                  <option value="3">For Sale</option>
                </select>
              </form>
            </div>
          </div> -->



          <?php
            foreach ($tweets as $tweet) {
                $v->insert('includes::tweet', ['tweet' =>  $tweet]);
            }
            ?>






        </div>
        <div class="row">
          <div class="col-sm-12">
            <nav class="pagination-a">
              <?php
              if ($total_pages >1) {
                  echo generatePageLinks($page, $total_pages, '/posts/');
              }
               ?>
            </nav>
          </div>
        </div>
      </div>
    </section><!-- End Property Grid Single-->





<?php $v->push('scripts') ?>
    <script>

    </script>
<?php $v->end() ?>
